version: '2'
services:
  web:
    build: .
    links:
      - database
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html:cached
    env_file:
      - .env
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasker
      MYSQL_USER: vykio
      MYSQL_PASSWORD: azerty123
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8002:80'
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database
volumes:
  data-volume:
